# Generated by Django 3.2.4 on 2021-07-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_auto_20210713_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_paid_total', models.FloatField()),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payment', to='accounts.vendor')),
            ],
        ),
    ]
