# Generated by Django 3.2.4 on 2021-08-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.URLField(default='https://stackoverflow.com/questions/10052220/advantages-to-using-urlfield-over-textfield'),
            preserve_default=False,
        ),
    ]
