# Generated by Django 3.2.4 on 2021-09-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210901_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
