# Generated by Django 3.2.4 on 2021-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_friends_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='online',
        ),
        migrations.AddField(
            model_name='friends',
            name='status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10),
        ),
    ]
