# Generated by Django 3.2.4 on 2021-09-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210921_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='status',
        ),
    ]
