# Generated by Django 3.1.7 on 2021-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210428_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
