# Generated by Django 3.1.7 on 2021-04-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(default='lol', max_length=50),
            preserve_default=False,
        ),
    ]
