# Generated by Django 3.1.7 on 2021-04-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210428_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_name',
        ),
    ]
