# Generated by Django 3.2.4 on 2021-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_vendor_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'This phone has already been registered.'}, max_length=15, null=True, unique=True),
        ),
    ]
