# Generated by Django 3.2.4 on 2021-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
