# Generated by Django 3.2.4 on 2021-07-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name_plural': '0. Vendor Auth Code'},
        ),
    ]
