# Generated by Django 3.2.4 on 2021-08-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
