# Generated by Django 3.2.4 on 2021-08-31 14:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default=accounts.models.user_name, max_length=20),
        ),
    ]
