# Generated by Django 3.2.4 on 2021-08-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '1. Author'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '3. Post'},
        ),
        migrations.AlterModelOptions(
            name='postview',
            options={'verbose_name_plural': '4. PostView'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
