# Generated by Django 3.2.4 on 2021-08-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210812_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Blog_Category',
        ),
    ]
