# Generated by Django 3.2.4 on 2021-08-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug-slugy', unique=True),
            preserve_default=False,
        ),
    ]
