# Generated by Django 3.2.4 on 2021-06-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210629_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='order_id',
        ),
    ]
