# Generated by Django 3.2.4 on 2021-06-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_payment_id_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='id', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(default='dd', max_length=250),
            preserve_default=False,
        ),
    ]
