# Generated by Django 3.2.4 on 2021-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210630_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='signature',
        ),
    ]
