# Generated by Django 3.2.4 on 2021-06-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_payment_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('RazorPay', 'RazorPay'), ('Stripe', 'Stripe')], default='Cash On Delivery', max_length=20),
        ),
    ]
