# Generated by Django 3.2.4 on 2021-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variant_amount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
