# Generated by Django 3.2.4 on 2021-07-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210713_2231'),
        ('order', '0020_orderproduct_variant_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orderproduct', to='accounts.vendor'),
        ),
    ]
