# Generated by Django 3.2.4 on 2021-06-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '6. Color'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '9. Comment'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '1. Product'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '7. Size'},
        ),
    ]
