# Generated by Django 3.2.4 on 2021-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210613_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
