# Generated by Django 3.2.4 on 2021-07-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile'),
        ('products', '0012_auto_20210708_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_variation', to='accounts.vendor'),
        ),
    ]
