# Generated by Django 3.2.4 on 2021-08-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Product short description'),
        ),
    ]
